apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapp-deployment
  labels:
    app: shield
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shield
  template:
    metadata:
      labels:
        app: shield
    spec:
      containers:
      - name: shield
        image: shield:1.2.3
        ports:
        - containerPort: 8080
        - containerPort: 8081
