apiVersion: v1
kind: Service
metadata:
  name: shield-service
spec:
  selector:
    app: shield
  type: NodePort
  ports:
    - name: default
      protocol: TCP
      port: 8080
      nodePort: 30007
    - name: admin
      protocol: TCP
      port: 8081
      nodePort: 30008
