apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldapp-deployment
  labels:
    app: shield
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shield
  template:
    metadata:
      labels:
        app: shield
    spec:
      containers:
      - name: shield
        image: registry.hub.docker.com/kaushik100/shield:1.4.0
        ports:
        - containerPort: 8080
        - containerPort: 8081
